name: Chirag's Daily Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Every day at 12:00 AM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Create file and commit
        run: |
          FILE="commit_number.md"

          if [ ! -f "$FILE" ]; then
            echo "Uploading Mark 24/7 project in git" > "$FILE"
            echo "commit number: 1" >> "$FILE"
          else
            CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")

            if [ -z "$CURRENT_COUNT" ]; then
              CURRENT_COUNT=0
            fi

            NEXT_COUNT=$((CURRENT_COUNT + 1))

            sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
          fi

          git config user.name "1nonlysho"
          git config user.email "chiragduhan2006@gmail.com"

          git add "$FILE"
          git commit -m "chore: daily auto commit"
          git push
